---
deployment:
  tasks:
    - export DEPLOYPATH=/home/c2540563c/public_html/testapp/
    - /bin/cp -a . $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
